import React from 'react';
import { useLocation } from '../../context/LocationContext';
import { 
  X, 
  Printer, 
  Download, 
  Sparkles, 
  Building, 
  ShieldAlert, 
  CheckCircle2,
  Activity
} from 'lucide-react';
import confetti from 'canvas-confetti';

export const ActionPlanModal = () => {
  const { 
    isActionPlanModalOpen, 
    setIsActionPlanModalOpen, 
    currentDistrict, 
    districtMetrics, 
    filteredVillages 
  } = useLocation();

  if (!isActionPlanModalOpen) return null;

  const handlePrint = () => {
    confetti({
      particleCount: 50,
      spread: 60,
      origin: { y: 0.5 }
    });
    window.print();
  };

  return (
    <div className="fixed inset-0 z-50 overflow-y-auto bg-slate-950/80 backdrop-blur-md flex items-center justify-center p-4">
      <div className="bg-slate-900 border border-slate-800 rounded-2xl max-w-3xl w-full p-6 space-y-6 shadow-2xl relative">
        
        {/* Header */}
        <div className="flex items-center justify-between border-b border-slate-800 pb-4">
          <div className="flex items-center space-x-3">
            <div className="w-10 h-10 rounded-xl bg-teal-500/20 border border-teal-500/40 flex items-center justify-center">
              <Activity className="w-6 h-6 text-teal-400" />
            </div>
            <div>
              <h3 className="text-lg font-black text-slate-100">
                Official District Health Action Plan (DHAP)
              </h3>
              <p className="text-xs text-slate-400">
                Generated by HealthBridge AI • {currentDistrict.name} District
              </p>
            </div>
          </div>

          <button
            onClick={() => setIsActionPlanModalOpen(false)}
            className="w-8 h-8 rounded-full bg-slate-800 hover:bg-slate-700 text-slate-300 flex items-center justify-center transition-all cursor-pointer"
          >
            <X className="w-4 h-4" />
          </button>
        </div>

        {/* Report Overview Box */}
        <div className="bg-slate-950 p-4 rounded-xl border border-slate-800 grid grid-cols-3 gap-3 text-center text-xs">
          <div>
            <span className="text-slate-400 block text-[10px]">District Scope</span>
            <strong className="text-slate-100 text-sm font-bold">{currentDistrict.name}</strong>
          </div>
          <div>
            <span className="text-slate-400 block text-[10px]">Monitored Villages</span>
            <strong className="text-teal-400 text-sm font-bold">{districtMetrics.totalVillages} Villages</strong>
          </div>
          <div>
            <span className="text-slate-400 block text-[10px]">High/Critical Priority</span>
            <strong className="text-red-400 text-sm font-bold">{districtMetrics.criticalCount + districtMetrics.highCount} Villages</strong>
          </div>
        </div>

        {/* Priority Interventions List */}
        <div className="space-y-3">
          <h4 className="text-xs font-bold text-slate-300 uppercase tracking-wider">
            Prioritized Clinical & Supply Interventions
          </h4>

          <div className="space-y-2 max-h-60 overflow-y-auto pr-1">
            {filteredVillages.map((village, idx) => (
              <div key={village.id} className="p-3 rounded-xl bg-slate-950 border border-slate-800 text-xs flex items-center justify-between">
                <div>
                  <div className="font-bold text-slate-100">{idx + 1}. {village.name} ({village.block} Block)</div>
                  <div className="text-[11px] text-amber-300/90">Bottleneck: {village.bottleneck}</div>
                </div>
                <div className="text-right">
                  <span className="font-semibold text-teal-300 block">{village.interventions[0]?.title}</span>
                  <span className="text-[10px] text-slate-400">Est. Cost: {village.interventions[0]?.estimatedCost}</span>
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* Actions */}
        <div className="pt-4 border-t border-slate-800 flex items-center justify-end space-x-3">
          <button
            onClick={() => setIsActionPlanModalOpen(false)}
            className="px-4 py-2 bg-slate-800 hover:bg-slate-700 text-slate-300 font-semibold text-xs rounded-xl transition-all cursor-pointer"
          >
            Close
          </button>
          <button
            onClick={handlePrint}
            className="px-5 py-2 bg-gradient-to-r from-teal-500 to-emerald-500 hover:from-teal-400 hover:to-emerald-400 text-slate-950 font-extrabold text-xs rounded-xl shadow-lg transition-all cursor-pointer flex items-center space-x-1.5"
          >
            <Printer className="w-4 h-4" />
            <span>Download & Print PDF</span>
          </button>
        </div>

      </div>
    </div>
  );
};
